version: '3.8'

services:
  postgres-zzz:
    image: postgres:15
    container_name: zzz_academy_db
    environment:
      POSTGRES_DB: zenless_db
      POSTGRES_USER: admin_zenless
      POSTGRES_PASSWORD: academy_password_123
    ports:
      - "5432:5432"
    volumes:
      - pgdata_zzz:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_zzz: