services:
  db:
    image: postgres:15-alpine
    container_name: zenless_academy_db
    restart: always
    environment:
      POSTGRES_USER: admin_zenless
      POSTGRES_PASSWORD: academy_password_123
      POSTGRES_DB: zenless_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: