spring.application.name=backend

# CONFIGURACIÓN DE BASE DE DATOS (POSTGRESQL - DOCKER)
spring.datasource.url=jdbc:postgresql://localhost:5432/zenless_db
spring.datasource.username=admin_zenless
spring.datasource.password=academy_password_123

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT CONFIG
jwt.secret=ZZZAcademySecretKeyForJwtTokensThatNeedsToBeLongEnoughToBeSecure1234!!
jwt.expirationMs=86400000
